skills = [
    "Cloud Platforms ",
    "• AWS Architectures ",
    "• AWS Serverless Application Model ",
    "• AWS S3 ",
    "• AWS EC2 ",
    "• AWS VPC ",
    "• Amazon ElastiCache ",
    "• Amazon Aurora ",
    "• AWS CloudFormation ",
    "• AWS Glue ",
    "• AWS Glue Data Catalog ",
    "• AWS Lambda ",
    "• AWS Step Functions ",
    "• AWS Kinesis Data Streams ",
    "• AWS SQS ",
    "• AWS SNS ",
    "• AWS Data Pipeline ",
    "• AWS EMR ",
    "• AWS Redshift ",
    "• AWS DynamoDB ",
    "• AWS SimpleDB ",
    "• AWS QuickSight ",
    "• AWS SageMaker ",
    "• Terraform ",
    " ",
    "Programming Languages & Frameworks ",
    "• Java ",
    "• J2EE ",
    "• SpringBoot ",
    "• Python ",
    "• SQL ",
    "• PySpark ",
    "• Apache Spark ",
    "• Databricks PySpark ",
    " ",
    "Data Engineering & Architecture ",
    "• ETL/ELT ",
    "• Data Mesh ",
    "• Microservices ",
    "• Data Governance ",
    "• Dimensional Data Modeling ",
    "• Metadata Management ",
    "• Data Lineage ",
    "• Schema Evolution ",
    "• Redshift Spectrum ",
    "• Medallion Data Lake Architecture ",
    "• Delta Lake ",
    "• Databricks Lakehouse ",
    "• OLTP ",
    "• OLAP ",
    "• Snowflake ",
    "• Segment CDP ",
    " ",
    "DevOps / CI/CD Tools ",
    "• Docker ",
    "• Kubernetes ",
    "• AWS ECR ",
    "• AWS ECS ",
    "• AWS EKS ",
    "• AWS Fargate ",
    "• Jenkins ",
    "• GitOps ",
    "• GitHub ",
    "• GitHub Actions ",
    "• Bitbucket ",
    "• JFrog Artifactory ",
    " ",
    "Machine Learning & Data Science ",
    "• AWS SageMaker ",
    "• Machine Learning ",
    "• Regression ",
    "• Classification ",
    "• CNN (Convolutional Neural Networks) ",
    "• Clustering ",
    "• Dimensionality Reduction ",
    "• PCA ",
    "• RAG ",
    "• NLP ",
    "• Encoding ",
    "• Embedding ",
    "• Bayesian K-means Clustering ",
    " ",
    "Data Visualization & Reporting ",
    "• Looker ",
    "• Tableau ",
    "• AWS QuickSight ",
    "• Amazon Athena ",
    "• PowerBI ",
    " ",
    "Security & Compliance ",
    "• SSL/TLS Authentication ",
    "• MFA ",
    "• JSON Web Tokens ",
    "• Cybersecurity ",
    "• CyberArk ",
    "• PII, PHI, PCI, HIPAA, GDPR Compliance ",
    "• Securing Patient Data ",
    "• FHIR ",
    "• HL7 ",
    " ",
    "Testing & Quality Assurance ",
    "• Unit Testing ",
    "• Integration Testing ",
    "• User Acceptance Testing (UAT) ",
    "• Deployment Smoke Testing ",
    "• A/B Testing ",
    "• Feature Flagging ",
    "• UX Testing ",
    " ",
    "Project Management & Collaboration Tools ",
    "• Agile Scrum SDLC ",
    "• Certified ScrumMaster ",
    "• MS Project ",
    "• Visio ",
    "• CloudCraft ",
    "• Office 365 ",
    "• Scheduling ",
    "• Budgets ",
    "• Milestones ",
    "• Risk Mitigation ",
    "• Stakeholder Management ",
    "• Confluence ",
    "• Jira ",
    " ",
    "Soft Skills ",
    "• Presentation Skills ",
    "• Communication Skills ",
    "• Writing Skills ",
    "• Leadership ",
    "• Resource Allocation ",
    "• Team Building ",
    "• Tutoring "
]

bulleted_skills = " ".join(skills)

print(bulleted_skills)
""